name: Continuous Integration Pipeline

on: [push]

jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules # Caching ~/.npm to accelerate CI
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - uses: actions/setup-node@v3
        with:
          node-version: "16.18"

      - name: Install Dependencies
        run: yarn
      - name: Run Unit tests
        run: yarn test
